
INSERT INTO  MATERIAL(MATERIALID,NAME,MATERIALTYPE,ISAVAILABLE) values ( 1,'Livre1','Livre', true );
INSERT INTO  MATERIAL(MATERIALID,NAME,MATERIALTYPE,ISAVAILABLE)values ( 2,'Livre2','Livre', true  );
INSERT INTO  MATERIAL(MATERIALID,NAME,MATERIALTYPE,ISAVAILABLE) values ( 3,'Livre3','Livre', true  );
INSERT INTO  MATERIAL(MATERIALID,NAME,MATERIALTYPE,ISAVAILABLE) values ( 4,'Chaise1','Chaise', true  );
INSERT INTO  MATERIAL(MATERIALID,NAME,MATERIALTYPE,ISAVAILABLE) values ( 5,'Chaise2','Chaise', true  );
INSERT INTO  MATERIAL(MATERIALID,NAME,MATERIALTYPE,ISAVAILABLE) values ( 6,'Chaise3','Chaise', true  );

INSERT INTO  USERS(USERID,NAME,PASSWORD,ROLE) values ( 1,'Admin1' ,'0000','ADMIN');
INSERT INTO  USERS(USERID,NAME,PASSWORD,ROLE) values ( 2,'User1','0000','USER' );
INSERT INTO  USERS(USERID,NAME,PASSWORD,ROLE) values ( 3,'User2','0000','USER' );

