DROP TABLE IF EXISTS MATERIEL;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ALLOCATION;

CREATE TABLE MATERIEL
(
    ID INT AUTO_INCREMENT PRIMARY KEY,

    NAME VARCHAR(250) NOT NULL,

    TYPE VARCHAR(250) NOT NULL,

    ETAT VARCHAR(250) NOT NULL

);


CREATE TABLE USER
(
    ID INT AUTO_INCREMENT PRIMARY KEY,

    USERNAME VARCHAR(250) NOT NULL,

    PASSWORD VARCHAR(250) NOT NULL,

    ROLE VARCHAR(250) NOT NULL

);


CREATE TABLE ALLOCATION
(
    ID INT AUTO_INCREMENT PRIMARY KEY,

    IDMATERIEL INT NOT NULL,

    IDUSER INT NOT NULL,

    DATEDEBUT DATE NOT NULL,

    DATEFIN DATE NOT NULL,

    FOREIGN KEY (IDMATERIEL) REFERENCES MATERIEL(ID),
    
    FOREIGN KEY (IDUSER) REFERENCES USER(ID)

);